---
settings:
  name: Astra Automation 22.08
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: rn/whats_new.html
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Astra Control Automation 22.08 docs
    url: "/index.html"
  - section: rn
  - section: intro
  - section: get-started
  - section: rest-core
  - section: endpoints
  - section: additional
  - section: workflows_infra
  - section: workflows
  - section: python
  - section: reference
  - section: information
  - title: Versiones anteriores
    url: "/aa-earlier-versions.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Funciones y beneficios
      url: "/intro/overview.html"
    - title: Antes de empezar
      url: "/get-started/before_get_started.html"
    - title: Obtenga un token de API
      url: "/get-started/get_api_token.html"
    - title: Hola mundo
      url: "/get-started/hello_world.html"
  - title: Implementaci贸n de REST
    links:
    - title: Servicios web REST
      url: "/rest-core/rest_web_services.html"
    - title: Detalles de HTTP
      url: "/rest-core/http_details.html"
    - title: Formato de URL
      url: "/rest-core/url_format.html"
  - title: Consideraciones adicionales
    links:
    - title: Seguridad RBAC
      url: "/additional/rbac.html"
    - title: Trabajar con colecciones
      url: "/additional/work_with_collections.html"
    - title: Diagn贸stico y soporte
      url: "/additional/diagnostics_support.html"
    - title: Revocar un token de API
      url: "/additional/revoke_token.html"
  - title: Recursos
    links:
    - title: Recursos Y colecciones PARA REST
      url: "/rest-core/resources_collections.html"
    - title: Resumen de recursos de Astra API
      url: "/endpoints/resources.html"
  - title: Flujos de trabajo
    links:
    - title: Preparaci贸n
      url: "/get-started/prepare_to_use_workflows.html"
    - title: Flujos de trabajo de infraestructura
      url: "/workflows_infra/workflows_infra_before.html"
    - title: Flujos de trabajo de gesti贸n
      url: "/workflows/workflows_before.html"
  - title: Python
    links:
    - title: Kit de desarrollo de software Astra Control Python de NetApp
      url: "/python/astra_toolkits.html"
    - title: Use Python de forma nativa
      url: "/python/python_before.html"
product-family:
  name: Astra
  repo: astra-family
